const mongoose = require('mongoose')
const dotenv = require('dotenv')
const db = require('./Config/database')
const express = require('express')
const app = express()
dotenv.config({path:'./config/.env'})
db()
app.listen(process.env.PORT,()=>{
    console.log('connected successfully at port',process.env.PORT)
})